name: Continuous Integration

on:
  push:
    branches:
      - '*'  # Runs CI on all branches
  pull_request:
    branches:
      - dev  # Runs CI before merging into dev

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install dependencies if using Python

      - name: Run tests
        run: |
          pytest  # Run unit tests
